### ISSUE TITLE
Syncing Issue - Having issues consistently

### ISSUE THREAD

**Issue by matt-dell** [MerginMaps/qgis-plugin#439]
I am having intermittent syncing issues which cripple my ability for myself or clients to effectively work on my projects.  This is the latest received after deleting my project of my PC and trying to sync from the Mergin cloud source. These issues seem to occur each time INPUT/MERGIN do an update.  This project worked fine on the INPUT app but is now corrupt with the new improved MERGIN app. 

Traceback (most recent call last):

  File "C:\Users/Valued Customer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 142, in download_timer_tick
    download_project_finalize(self.job)

  File "C:\Users/Valued Customer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 216, in download_project_finalize
    task.apply(job.directory, job.mp)

  File "C:\Users/Valued Customer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 269, in apply
    mp.geodiff.make_copy_sqlite(mp.fpath(self.file_path), mp.fpath_meta(self.file_path))

  File "C:\Users/Valued Customer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 221, in make_copy_sqlite
    return self.clib.make_copy_sqlite(src, dst)

  File "C:\Users/Valued Customer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 328, in make_copy_sqlite
    _parse_return_code(res, "make_copy_sqlite")

  File "C:\Users/Valued Customer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 41, in _parse_return_code
    raise GeoDiffLibError(msg)

Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: make_copy_sqlite

**Comment by VikingHome1** [comment]
try reinstalling python and the repo, it might interpret it with no errors, reply to this if my answer doesn't work (most likely won't work, but on and off is always something you should try if you don't know the answer already)

**Comment by PeterPetrik** [comment]
Hi, can you try to remove mergin-plugin from QGIS, restart QGIS and install it again?
