### ISSUE TITLE
Timeout issues

### ISSUE THREAD

**Issue by andresgarcia25** [MerginMaps/qgis-plugin#456]
We are experiencing constant timeout issues when trying to download and sync from our own instance of Mergin CE.

The server is accessible (Test Connection OK) and people can sync changes correctly from their devices with Mergin Maps Input app installed.

The issues appear mostly when trying to download new projects from the server with multiple images (~5GB) from Mergin Maps QGIS plugin:

- When trying to read My projects or Shared with me, the message 'Error: The read operation timed out' appears.

- After multiple Reload attempts, we can start the download, which ends up failing with the following message:

```
Traceback (most recent call last):

  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 126, in download_timer_tick
    is_running = download_project_is_running(self.job)

  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 187, in download_project_is_running
    raise future.exception()

  File "C:\OSGeo4W\apps\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)

  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 92, in _do_download
    item.download_blocking(mc, mp, project_path)

  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 295, in download_blocking
    resp = mc.get(

  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 207, in get
    return self._do_request(request)

  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 181, in wrapper
    return f(self, *args)

  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 192, in _do_request
    return self.opener.open(request)

  File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)

  File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +

  File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)

  File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,

  File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 1350, in do_open
    r = h.getresponse()

  File "C:\OSGeo4W\apps\Python39\lib\http\client.py", line 1345, in getresponse
    response.begin()

  File "C:\OSGeo4W\apps\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()

  File "C:\OSGeo4W\apps\Python39\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")

  File "C:\OSGeo4W\apps\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)

  File "C:\OSGeo4W\apps\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)

  File "C:\OSGeo4W\apps\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

socket.timeout: The read operation timed out
```

**Comment by tomasMizera** [comment]
Hi, please reopen in case this is still hapenning
