### ISSUE TITLE
Failed to sync project Lithos Geological/MTB_Telegraph_v1.3 due to an unhandled exception.

### ISSUE THREAD

**Issue by geoclimb-andrew** [MerginMaps/qgis-plugin#510]
Traceback (most recent call last):

  File "C:\Users/geocl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 199, in push_timer_tick
    is_running = push_project_is_running(self.job)

  File "C:\Users/geocl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_push.py", line 219, in push_project_is_running
    raise future.exception()

  File "C:\OSGeo4W\apps\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)

  File "C:\Users/geocl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_push.py", line 317, in _do_upload
    item.upload_blocking(job.mc, job.mp)

  File "C:\Users/geocl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_push.py", line 68, in upload_blocking
    resp = mc.post("/v1/project/push/chunk/{}/{}".format(self.transaction_id, self.chunk_id), data, headers)

  File "C:\Users/geocl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 223, in post
    return self._do_request(request)

  File "C:\Users/geocl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 190, in wrapper
    return f(self, *args)

  File "C:\Users/geocl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 201, in _do_request
    return self.opener.open(request)

  File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)

  File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +

  File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)

  File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,

  File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 1350, in do_open
    r = h.getresponse()

  File "C:\OSGeo4W\apps\Python39\lib\http\client.py", line 1345, in getresponse
    response.begin()

  File "C:\OSGeo4W\apps\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()

  File "C:\OSGeo4W\apps\Python39\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")

  File "C:\OSGeo4W\apps\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)

  File "C:\OSGeo4W\apps\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)

  File "C:\OSGeo4W\apps\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by tomasMizera** [comment]
Thank you for the report, the issue with "unhandled exception" is now fixed. Please reach out to our support at [support@merginmaps.com](mailto:support@merginmaps.com) if you still have issues.
