### ISSUE TITLE
Mergin Maps Synchronization to cloud folder failed - Failed to download project due to an unhandled exception

### ISSUE THREAD

**Issue by Ronnie2024** [MerginMaps/qgis-plugin#553]
- Failed to download project due to an unhandled exception.

Traceback (most recent call last):

  File "C:\Users/reyesr4454/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 129, in download_timer_tick
    is_running = download_project_is_running(self.job)

  File "C:\Users/reyesr4454/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 186, in download_project_is_running
    _cleanup_failed_download(job.directory, job.mp)

  File "C:\Users/reyesr4454/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 106, in _cleanup_failed_download
    shutil.rmtree(directory)

  File "C:\PROGRA~1\QGIS32~1.11\apps\Python39\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)

  File "C:\PROGRA~1\QGIS32~1.11\apps\Python39\lib\shutil.py", line 618, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())

  File "C:\PROGRA~1\QGIS32~1.11\apps\Python39\lib\shutil.py", line 616, in _rmtree_unsafe
    os.unlink(fullname)

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\reyesr4454\\OneDrive - ARCADIS\\Desktop\\QGIS\\Oceanside\\address.dbf.1.0'

QGIS version 3.28.11
Windows 11 Enterprise
Mergin version 2023.4.1

**Comment by wonder-sk** [comment]
@Ronnie2024 thanks for reporting this issue. It is a known problem that services like OneDrive or Dropbox may interfere with the sync done by Mergin Maps QGIS plugin, and it looks like your project is stored in the OneDrive directory. The best solution is to keep the project data in a directory that is not a part of OneDrive, or alternatively pause syncing of OneDrive temporarily while doing work with Mergin Maps.

**Comment by Ronnie2024** [comment]
Hi @wonder-sk the other 10 projects does not have a problem synching the Mergin Map. Only this 1 project, is the loading of data can be a source of this problem?
