### ISSUE TITLE
No projects available in QGIS Browser

### ISSUE THREAD

**Issue by rphenriques** [MerginMaps/qgis-plugin#559]
The QGIS browser entry stopped listing (any) projects, either local or on the server. Tried re-installing the plugin and then updating QGIS to the latest version. "Explore public projects" option works but extremely slow.

While trying to use the QGIS browser option, the following error occurs:

```
2024-01-15T12:16:34     WARNING    An error has occurred while executing Python code:
             
             
             TypeError: __init__() takes from 1 to 6 positional arguments but 7 were given
             
             
             Traceback (most recent call last):
              File "/Users/rph/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Mergin/plugin.py", line 939, in createChildren
              return self.createChildrenGroups()
              File "/Users/rph/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Mergin/plugin.py", line 971, in createChildrenGroups
              my_projects = MerginGroupItem(self, "My projects", "created", "user.svg", 1, self.plugin)
              File "/Users/rph/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Mergin/plugin.py", line 1105, in __init__
              MerginRootItem.__init__(self, parent, grp_name, grp_filter, icon, order, plugin)
             TypeError: __init__() takes from 1 to 6 positional arguments but 7 were given
             
             
             
             
             Python version: 3.9.5 (default, Sep 10 2021, 16:18:19) 
             [Clang 12.0.5 (clang-1205.0.22.11)]
             
             
             QGIS version: 3.34.2-Prizren Prizren, 7d199797fcc
             
             
             Python Path:
             
             /Applications/QGIS.app/Contents/MacOS/../Resources/python/Users/rph/Library/Application Support/QGIS/QGIS3/profiles/default/python/Users/rph/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/Applications/QGIS.app/Contents/MacOS/lib/python3.9/lib-dynload/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg/Applications/QGIS.app/Contents/MacOS/lib/python3.9/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Applications/QGIS.app/Contents/MacOS/lib/python39.zip/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg/Users/rph/Library/Application Support/QGIS/QGIS3/profiles/default/python
```

**Comment by ValentinBuira** [comment]
Hi @rphenriques, I could not reproduce it on latest master. Is the bug still reproducible on latest version ?

**Comment by rphenriques** [comment]
Hi @ValentinBuira, yes, it's still there. Just today (coincidentally) a colleague had the exact same bug and applied the change I've submitted in the pull request to fix it. He's using QGIS 3.38 and Mergin Maps Plugin 2024.2 on a Mac M1, with MacOS Sonoma 14.5.

**Comment by tomasMizera** [comment]
Hi @rphenriques, apologies for the delayed response to your issue (and PR). We reviewed the code today and found that the issue stems from handling deprecated server versions (`< 2023.2.0`). This code - and support for these older server versions - is scheduled for removal in the next QGIS plugin release (see https://github.com/MerginMaps/qgis-plugin/issues/683).

I strongly recommend upgrading your server to a newer version to ensure you receive important updates and to prevent this issue from occurring.

I'll go ahead and close the ticket and PR, but feel free to reopen the ticket if you still experience issues with the latest server version.
