### ISSUE TITLE
Project Sync Issue

### ISSUE THREAD

**Issue by Nathan-LloydBore** [MerginMaps/qgis-plugin#560]
Since the last successful sync, I have imported a DXF into a geopackage stored inthe project directory/External Documents folder listed below.
I have had to remove the project name from below and cannot disclose the name of the file I don't believe. The file name is quite long though so I am wondering if there is a character limit that has caused this issue?
The issue reoccurs every time I try to sync this project now.

Error log:
```
Traceback (most recent call last):

  File "C:\Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python/plugins\Mergin\sync_dialog.py", line 174, in push_start_internal
    self.job = push_project_async(self.mergin_client, self.target_dir)

  File "C:\Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python/plugins\Mergin\mergin\client_push.py", line 117, in push_project_async
    changes = mp.get_push_changes()

  File "C:\Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python/plugins\Mergin\mergin\merginproject.py", line 327, in get_push_changes
    size, checksum = do_sqlite_checkpoint(self.fpath(file["path"]), self.log)

  File "C:\Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python/plugins\Mergin\mergin\utils.py", line 96, in do_sqlite_checkpoint
    cursor.execute("VACUUM")

sqlite3.OperationalError: attempt to write a readonly database.
```

Stack Trace:
```
An error has occurred while executing Python code: 

sqlite3.OperationalError: attempt to write a readonly database 
Traceback (most recent call last):
  File "C:\Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python/plugins\Mergin\plugin.py", line 461, in current_project_sync
    self.manager.project_status(self.mergin_proj_dir)
  File "C:\Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python/plugins\Mergin\projects_manager.py", line 181, in project_status
    self.sync_project(project_dir)
  File "C:\Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python/plugins\Mergin\projects_manager.py", line 244, in sync_project
    pull_changes, push_changes, push_changes_summary = self.mc.project_status(project_dir)
  File "C:\Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python/plugins\Mergin\mergin\client.py", line 826, in project_status
    push_changes = mp.get_push_changes()
  File "C:\Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python/plugins\Mergin\mergin\merginproject.py", line 327, in get_push_changes
    size, checksum = do_sqlite_checkpoint(self.fpath(file["path"]), self.log)
  File "C:\Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python/plugins\Mergin\mergin\utils.py", line 96, in do_sqlite_checkpoint
    cursor.execute("VACUUM")
sqlite3.OperationalError: attempt to write a readonly database


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.0-Firenze Firenze, ed3ad0430f3 

Python Path:
C:\Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python/plugins\TomBio
C:\Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python/plugins\road_slope_calculator
C:\Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python/plugins\postgis_toolbox
C:\Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python/plugins\lftools
C:\Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python/plugins\LandSurveyCodesImport
C:\Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python/plugins\geoprocalgos
C:/PROGRA~1/QGIS32~1.0/apps/qgis/./python
C:/Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python
C:/Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python/plugins
C:/PROGRA~1/QGIS32~1.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.28.0\bin\python39.zip
C:\PROGRA~1\QGIS32~1.0\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib
C:\Program Files\QGIS 3.28.0\bin
C:\Users\Nathan\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS32~1.0\apps\Python39
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python
C:\Users\Nathan\AppData\Roaming\QGIS\QGIS3\profiles\Nathan\python\plugins\assets\external\xmltodict-0.13.0-py2.py3-none-any.whl
C:\Users\Nathan\AppData\Roaming\QGIS\QGIS3\profiles\Nathan\python\plugins\assets\external\aenum-3.1.11-py3-none-any.whl
C:\Users\Nathan\AppData\Roaming\QGIS\QGIS3\profiles\Nathan\python\plugins\DigitizingTools\tools
C:\Users\Nathan\AppData\Roaming\QGIS\QGIS3\profiles\Nathan\python\plugins\DigitizingTools
C:\Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python/plugins\geosys-plugin
C:\Users\Nathan\AppData\Roaming\QGIS\QGIS3\profiles\Nathan\python\plugins
C:\Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python/plugins\joinmultiplelines
C:\Users/Nathan/AppData/Roaming/QGIS/QGIS3\profiles\Nathan/python/plugins\LandSurveyCodesImport\gui
.
C:\Users\Nathan\AppData\Roaming\QGIS\QGIS3\profiles\Nathan\python\plugins\mmqgis/forms
C:\Users\Nathan\AppData\Roaming\QGIS\QGIS3\profiles\Nathan\python\plugins\qfieldsync\libqfieldsync.whl
C:\Users\Nathan\AppData\Roaming\QGIS\QGIS3\profiles\Nathan\python\plugins
C:/Users/Nathan/OneDrive - Lloyd Bore Ltd/Documents/5. Mergin/Mergin Local Projects/ProjectName
```

**Comment by tomasMizera** [comment]
Hi @Nathan-LloydBore, sorry for late reply. There is a 260 characters limit on Windows. Feel free to reopen if you still have issues.
