### ISSUE TITLE
Can't download project file.

### ISSUE THREAD

**Issue by EnergyWarrior** [MerginMaps/qgis-plugin#565]
Hi there,

I've been stuck on downloading project from mergimmaps server. The download process always stuck around 21% and these message appeared:

Traceback (most recent call last):

  File "C:\Users/Maxwell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 201, in _do_request
    return self.opener.open(request)

  File "C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)

  File "C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(

  File "C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)

  File "C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)

  File "C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users/Maxwell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 129, in download_timer_tick
    is_running = download_project_is_running(self.job)

  File "C:\Users/Maxwell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 187, in download_project_is_running
    raise future.exception()

  File "C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)

  File "C:\Users/Maxwell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 92, in _do_download
    item.download_blocking(mc, mp, project_path)

  File "C:\Users/Maxwell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 299, in download_blocking
    resp = mc.get(

  File "C:\Users/Maxwell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 216, in get
    return self._do_request(request)

  File "C:\Users/Maxwell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 190, in wrapper
    return f(self, *args)

  File "C:\Users/Maxwell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 205, in _do_request
    raise ClientError(info.get("detail"))

Mergin.mergin.common.ClientError: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

How to get over this problem? since I've been unable to download the project manually from webservice.

Thank you very much.

**Comment by wojtek19022** [comment]
I have similar issue
```Traceback (most recent call last):

  File "C:\Users/wojta/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 201, in _do_request
    return self.opener.open(request)

  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)

  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(

  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)

  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)

  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

urllib.error.HTTPError: HTTP Error 404: NOT FOUND


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "C:\Users/wojta/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 129, in download_timer_tick
    is_running = download_project_is_running(self.job)

  File "C:\Users/wojta/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 187, in download_project_is_running
    raise future.exception()

  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)

  File "C:\Users/wojta/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 92, in _do_download
    item.download_blocking(mc, mp, project_path)

  File "C:\Users/wojta/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 299, in download_blocking
    resp = mc.get(

  File "C:\Users/wojta/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 216, in get
    return self._do_request(request)

  File "C:\Users/wojta/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 190, in wrapper
    return f(self, *args)

  File "C:\Users/wojta/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 205, in _do_request
    raise ClientError(info.get("detail"))

Mergin.mergin.common.ClientError: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.```
