### ISSUE TITLE
Failed to sync project due to an unhandled exception.

### ISSUE THREAD

**Issue by vtebbitt** [MerginMaps/qgis-plugin#571]
Traceback (most recent call last):

  File "C:\Users/tebbi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 275, in pull_timer_tick
    is_running = pull_project_is_running(self.job)

  File "C:\Users/tebbi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 527, in pull_project_is_running
    raise future.exception()

  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)

  File "C:\Users/tebbi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 95, in _do_download
    item.download_blocking(mc, mp, project_path)

  File "C:\Users/tebbi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 324, in download_blocking
    save_to_file(resp, self.download_file_path)

  File "C:\Users/tebbi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\utils.py", line 39, in save_to_file
    with open(path, "wb") as output:

OSError: [Errno 22] Invalid argument: 'C:\\Users\\tebbi\\Corstown_Bridge\\.mergin\\fetch_v30-v33\\Paths_2024-01-26T15:55:43.618.jpg.0'

**Comment by tomasMizera** [comment]
This one somehow slipped through, sorry @vtebbitt! It seems like a wrong file name, try removing the `:` sign from the image
