### ISSUE TITLE
Unable to download or sync some projects due to format_exception()

### ISSUE THREAD

**Issue by raherin** [MerginMaps/qgis-plugin#573]
Some projects cannot be downloaded or synchronised using the plugin. The error output is as follows:

```
Traceback (most recent call last):

  File "C:\Users/raahe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 135, in download_timer_tick
    is_running = download_project_is_running(self.job)

  File "C:\Users/raahe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 203, in download_project_is_running
    "Error while downloading project: " + "".join(traceback.format_exception(future.exception()))

TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb' 
```

**Comment by raherin** [comment]
Closing this ticket as it's related to a file naming error.
