### ISSUE TITLE
Failed to download project due to an unhandled exception.

### ISSUE THREAD

**Issue by sfernandesgmbp** [MerginMaps/qgis-plugin#578]
Could be other issues but QGIS version is on 3.28.12 and was used 2 weeks prior. Anyone else having this issue?

**Comment by wonder-sk** [comment]
@sfernandesgmbp do you have any further details about the error?

**Comment by drekseimertutje** [comment]
In QGIS 3.22.14 error while downloading project from Browser panel. 
I had a project with the same name opened. 
When I restarted QGIS without a project opened, tried again to download and then the download succeeded. 

Traceback (most recent call last):

  File "C:\Users/****/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 135, in download_timer_tick
    is_running = download_project_is_running(self.job)

  File "C:\Users/****/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 203, in download_project_is_running
    "Error while downloading project: " + "".join(traceback.format_exception(future.exception()))

TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'

**Comment by tomasMizera** [comment]
Should be fixed now with https://github.com/MerginMaps/python-api-client/pull/201
