### ISSUE TITLE
Problems syncing a QGIS project to MerginMaps

### ISSUE THREAD

**Issue by styrke10** [MerginMaps/qgis-plugin#580]
Hi,

A client of mine has problems synchronizing his QGIS project to MerginMaps after having made a few changes to the setup of a couple of layers.

The sync process fails with the following error:
"Failed to sync project MoorAdvice WorkSpace/kbh_kommune_kaempe_bjorneklo due to an unhandled exception."

I have copied in the traceback below:
----------------------------------------------------------
Traceback (most recent call last):

  File "C:\Users/TheisDahm-Naturbyg/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 275, in pull_timer_tick
    is_running = pull_project_is_running(self.job)

  File "C:\Users/TheisDahm-Naturbyg/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 527, in pull_project_is_running
    raise future.exception()

  File "C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)

  File "C:\Users/TheisDahm-Naturbyg/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 95, in _do_download
    item.download_blocking(mc, mp, project_path)

  File "C:\Users/TheisDahm-Naturbyg/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 324, in download_blocking
    save_to_file(resp, self.download_file_path)

  File "C:\Users/TheisDahm-Naturbyg/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\utils.py", line 39, in save_to_file
    with open(path, "wb") as output:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\TheisDahm-Naturbyg\\Natur Gruppen Holding\\NB Teammappe Jacob M - Dokumenter\\København Kommune\\Invasive arter\\Kortlægning\\Mergin Maps\\kbh_kommune_kaempe_bjorneklo\\.mergin\\fetch_v6-v8\\Kaempe_Bjorneklo_1_10.gpkg-diff-330f2308-eb4b-4068-9f56-03e57a7c97a2.0'
--------------------------------------------------

Can you spot the problem?

Kind regards,
Morten Storm

**Comment by erpas** [comment]
They need to shorten the project folder path - it exceeds 260 characters limit for Windows OS.

See https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation

**Comment by styrke10** [comment]
Thanks a lot – sounds like an easy fix!

 

Bedste hilsner,

Morten

 

--

Morten Storm

Styrke 10 ApS



House of Innovation | Jernbanegade 27 | 6000 Kolding

 

www:  <https://styrke10.dk/> https://styrke10.dk

m: 51 51 09 29

 



 

Fra: Radek Pasiok ***@***.***> 
Sendt: 23. maj 2024 11:58
Til: MerginMaps/qgis-plugin ***@***.***>
Cc: Morten Storm ***@***.***>; Author ***@***.***>
Emne: Re: [MerginMaps/qgis-plugin] Problems syncing a QGIS project to MerginMaps (Issue #580)

 

They need to shorten the project folder path - it exceeds 260 characters limit for Windows OS.

See https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation
