### ISSUE TITLE
Error when trying to delete a project

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/qgis-plugin#582]
when i'm done with a project and choose to remove locally - i keep getting this python error2024-05-23T09:37:10   WARNING   Traceback (most recent call last):
       File "C:\Users/jesse/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\plugin.py", line 769, in
       QTimer.singleShot(250, lambda: shutil.rmtree(self.path))
       File "C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\shutil.py", line 759, in rmtree
       return _rmtree_unsafe(path, onerror)
       File "C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\shutil.py", line 624, in _rmtree_unsafe
       _rmtree_unsafe(fullname, onerror)
       File "C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\shutil.py", line 629, in _rmtree_unsafe
       onerror(os.unlink, fullname, sys.exc_info())
       File "C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\shutil.py", line 627, in _rmtree_unsafe
       os.unlink(fullname)
       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:/Users/USR/Documents/Active QGIS Projects\\2-12-4-34w1 - 2024 PII - Mergin\\.mergin\\client-log.txt'

**Comment by erpas** [comment]
It is still an issue. Steps to reproduce (as above):

- open a MM project
- sync it
- open another QGIS project or start a new one
- try to remove the MM project locally using QGIS Browser (right-click on the project item and Remove locally)
