### ISSUE TITLE
unable to create a diff between two versions in the QGIS plugin

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/qgis-plugin#588]
1. I have created a simple project with 1 survey layer 
2. synchronized new version V2. in which I have added 3 new points 
3. synchronized new version V3. in which I have updated 1 point (from the previous version), deleted 1 point (from the previous version), added 1 new point 
4. I tried to create a difference between these two versions as described in this test 
<img width="532" alt="image" src="https://github.com/MerginMaps/qgis-plugin/assets/94351263/c7bc386e-f943-430c-b1cd-84f46a07dff2">
<img width="1398" alt="image" src="https://github.com/MerginMaps/qgis-plugin/assets/94351263/2fdde0e4-5011-4830-a6fa-0d9dcf039f19">

However, after I pressed "run" I got this error 
<img width="532" alt="image" src="https://github.com/MerginMaps/qgis-plugin/assets/94351263/1cc19398-9f6c-463a-940a-db01bc065020">
Here is the error in text form:
Traceback (most recent call last):
File "/Users/patrikmizera/Library/Application Support/QGIS/QGIS3/profiles/test01/python/plugins/Mergin/processing/algs/create_diff.py", line 149, in processAlgorithm
features = diff_table_to_features(diff[table_name], db_schema[table_name], fields, fields_mapping, db_conn)
File "/Users/patrikmizera/Library/Application Support/QGIS/QGIS3/profiles/test01/python/plugins/Mergin/diff.py", line 231, in diff_table_to_features
wkb_with_gpkg_hdr = base64.decodebytes(value.encode("ascii"))
AttributeError: 'NoneType' object has no attribute 'encode'

Execution failed after 1.53 seconds

Mergin plugin artefact: https://github.com/MerginMaps/qgis-plugin/actions/runs/9482639845
Tested on MAC against app.dev (version with the new editor role)

**Comment by MarcelGeo** [comment]
Issue is occuring also on currently released plugin. Therefore not related to editor implementations.
