### ISSUE TITLE
unable to Extract local changes in the QGIS plugin

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/qgis-plugin#589]
1. I have created a simple project with 1 survey layer
2. synchronized new version V2. in which I have added 3 new points
3. I have updated 1 point (from the previous version), deleted 1 point (from the previous version), added 1 new point, after that I have saved the project and did not sync 
4. I tried to extract local changes as described in this test
<img width="532" alt="image" src="https://github.com/MerginMaps/qgis-plugin/assets/94351263/8ef25ebf-de7f-4ca5-80c4-87ff62f24d81">
<img width="1353" alt="image" src="https://github.com/MerginMaps/qgis-plugin/assets/94351263/9574cc82-e7f5-43f3-bfe4-714341dd688f">

After I hit "run" I got this error: 
<img width="684" alt="image" src="https://github.com/MerginMaps/qgis-plugin/assets/94351263/981d44d4-43ae-40ee-b761-0c702cff5062">

Here is the error in text form: 
Traceback (most recent call last):
File "/Users/patrikmizera/Library/Application Support/QGIS/QGIS3/profiles/test01/python/plugins/Mergin/processing/algs/extract_local_changes.py", line 118, in processAlgorithm
features = diff_table_to_features(diff[table_name], db_schema[table_name], fields, fields_mapping, db_conn)
File "/Users/patrikmizera/Library/Application Support/QGIS/QGIS3/profiles/test01/python/plugins/Mergin/diff.py", line 231, in diff_table_to_features
wkb_with_gpkg_hdr = base64.decodebytes(value.encode("ascii"))
AttributeError: 'NoneType' object has no attribute 'encode'

Execution failed after 0.09 seconds

Mergin plugin artefact: https://github.com/MerginMaps/qgis-plugin/actions/runs/9482639845
Tested on MAC against app.dev (version with the new editor role)

**Comment by MarcelGeo** [comment]
Issue is occuring also on currently released plugin. Therefore, this is not related to editor implementations.
