### ISSUE TITLE
Failed to sync project due to an unhandled exception.

### ISSUE THREAD

**Issue by ulfboge** [MerginMaps/qgis-plugin#629]
Dear Mergin Maps,

This happened when I tried to sync the project with QGIS after updates had been made in the field: 

Traceback (most recent call last):

  File "C:\Users/galag/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 290, in pull_timer_tick
    self.pull_conflicts = pull_project_finalize(self.job)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users/galag/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 639, in pull_project_finalize
    shutil.rmtree(job.temp_dir)

  File "C:\OSGeo4W\apps\Python312\Lib\shutil.py", line 781, in rmtree
    return _rmtree_unsafe(path, onexc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\OSGeo4W\apps\Python312\Lib\shutil.py", line 639, in _rmtree_unsafe
    onexc(os.rmdir, path, err)

  File "C:\OSGeo4W\apps\Python312\Lib\shutil.py", line 637, in _rmtree_unsafe
    os.rmdir(path)

PermissionError: [WinError 5] Access is denied: 'C:\\Users\\galag\\KAYA Climate Solutions GmbH\\Climate Office - Documents\\General\\Map projects\\Rupa\\fire-survey\\fire-survey\\.mergin\\fetch_v32-v33'

Kind regards,
Johan

**Comment by ValentinBuira** [comment]
I think that could be the same error as #613 and I couldn't pin down the issue

Does that folder is in some onedrive/dropbox/google drive - synced folder that could be the issue?

Otherwise if you are allow to share the project, do you think you could : 
  *  share the Mergin project with me - my mergin username is "ValentinB_lutra" (reader permission would be enough) - https://help.cloudmergin.com/sharing-project
 *  zip the folder with your data (content of C:\Users\galag\KAYA Climate Solutions GmbH\Climate Office - Documents\General\Map projects\Rupa\fire-survey\fire-survey folder) and send it to me for further analysis: valentin dot buira at lutraconsulting dot co dot uk

**Comment by tomasMizera** [comment]
Hi everyone, we've made several updates to the sync process, please reach out to our support team at support@merginmaps.com if you still have issues. Thank you for the report!
