### ISSUE TITLE
Download through mergin plugin fails after reaching 100% with unhandled exception

### ISSUE THREAD

**Issue by etiennethomassen** [MerginMaps/qgis-plugin#631]
Downloading a large and active Mergin project fails after reaching 100% with an unhandled exception

Traceback (most recent call last):

  File "C:\Users/etienne/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 150, in download_timer_tick
    download_project_finalize(self.job)

  File "C:\Users/etienne/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 239, in download_project_finalize
    task.apply(job.directory, job.mp)

  File "C:\Users/etienne/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 286, in apply
    file_to_merge.merge()

  File "C:\Users/etienne/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 570, in merge
    raise ClientError("Download of file {} failed. Please try it again.".format(self.dest_file))

Mergin.mergin.common.ClientError: Detail: Download of file C:\Users\etienne\Documents\GIS\LCF_bostracken\LCF_bostracken\bostracken.qgz failed. Please try it again.

**Comment by tomasMizera** [comment]
Hi @etiennethomassen, I have forwarded your query to support. They will get in touch soon

**Comment by erpas** [comment]
Hi Etienne,

Can you please share diagnostic log from your machine where you experienced the problem?
Please see:
https://merginmaps.com/docs/misc/troubleshoot/#diagnostic-logs
Please make sure to mention your username and date when the log was created so we can correctly relate it with your problem.

It is up to you whether to continue here in GitHub or create a more private support ticket in our helpdesk:
https://support.merginmaps.com/support/tickets/new

**Comment by etiennethomassen** [comment]
Ok. I have created a ticket with the requested log in the attachement.

**Comment by tomasMizera** [comment]
Great, thanks for you cooperation. I am closing this GitHub ticket then
