### ISSUE TITLE
QGIS not sychronising mergin project

### ISSUE THREAD

**Issue by FelipeGarciaFons** [MerginMaps/qgis-plugin#647]
See error report. Anyone can help  resolve this technically? I do not have expertise in code writing. Thanks

Traceback (most recent call last):

  File "C:\Users/bfgf/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 275, in pull_timer_tick
    is_running = pull_project_is_running(self.job)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users/bfgf/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 527, in pull_project_is_running
    raise future.exception()

  File "C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users/bfgf/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 95, in _do_download
    item.download_blocking(mc, mp, project_path)

  File "C:\Users/bfgf/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 324, in download_blocking
    save_to_file(resp, self.download_file_path)

  File "C:\Users/bfgf/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\utils.py", line 39, in save_to_file
    with open(path, "wb") as output:
         ^^^^^^^^^^^^^^^^

FileNotFoundError: [Errno 2] No such file or directory: '\\\\kh-srv-827\\userdata$\\bfgf\\My Documents\\Mergin\\B24079\\B24079_inventaris_straatbomen_Gent_2024_4\\.mergin\\fetch_v2-v347\\inventarisatie_controle_straatbomen_Gent_2024_—_inventarisatie_controle_straatbomen_gent_2024.gpkg-diff-19af1c04-b180-4f5b-9c94-a679ce084c33.0'

**Comment by ValentinBuira** [comment]
Hi @FelipeGarciaFons, thanks for the bug report, However I was not able reproduce the issue on my side, with the current information. could you please : 
 *  submit diagnostic log from the plugin - see https://help.cloudmergin.com/plugin-logs
 * if possible,  share the Mergin project with me - my mergin username is "ValentinB_lutraconsulting" (reader permission would be enough) - https://help.cloudmergin.com/sharing-project

**Comment by FelipeGarciaFons** [comment]
We made a new version of the project and shared this new version and
problem sold

Op wo 8 jan 2025, 13:42 schreef VJohnson123 ***@***.***>:
