### ISSUE TITLE
Failed to download project due to an unhandled exception but other projects are ok

### ISSUE THREAD

**Issue by chantoniou** [MerginMaps/qgis-plugin#651]
Failed to download project YYCY/Larnaka Monitoring due to an unhandled exception.

Traceback (most recent call last):

  File "C:\Users/chris/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 150, in download_timer_tick
    download_project_finalize(self.job)

  File "C:\Users/chris/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 239, in download_project_finalize
    task.apply(job.directory, job.mp)

  File "C:\Users/chris/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 286, in apply
    file_to_merge.merge()

  File "C:\Users/chris/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 570, in merge
    raise ClientError("Download of file {} failed. Please try it again.".format(self.dest_file))

Mergin.mergin.common.ClientError: Detail: Download of file C:\Users\chris\OneDrive\Desktop\MELC\MELC QGIS online\Larnaka Monitoring\Larnaka Monitoring.qgz failed. Please try it again.

**Comment by ValentinBuira** [comment]
Hi @chantoniou thanks for the bug report, we had a multiple tickets related to OneDrive, do you think you could try to download the project in a folder outside of your OneDrive folder (in your exemple  outside of \Chris\OneDrive) and if it's still happening
